# Mod properties
group = rearth.oritech
mod_id = oritech
version = 1.2.7
archives_base_name = oritech

# Minecraft properties
minecraft_version = 1.20.1
parchment_mappings = 2023.09.03

# Loaders
forge_version = 47.4.0

# Plugin versions (managed in settings.gradle repos)
autoServiceVersion = 1.1.1

# Common Dependencies
architectury_version = 9.2.12
geckolib_version = 4.0.4
emi_version = 1.1.15+1.20.1
rei_version = 12.1.715
jei_version = 15.20.0.105

# Forge Config API Port (for Fabric compat - not used in forge-only build, kept for reference)
forge_config_api_port_version = 8.0.0

# Recipe Viewer Preference
# Available: emi, rei, jei or disabled
recipe_viewer = emi

# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
